### ISSUE TITLE
更换backbone

### ISSUE THREAD

**Issue by liliwannian** [zf020114/DARDet#11]
您好，我想把您代码中的backbone从resnet50换成resnet34。
![image](https://user-images.githubusercontent.com/71505396/143517045-9e08d685-f959-4f5f-927a-62468a5eb613.png)
修改了pretrained和depth这两个地方。但是出现以下错误：
```
Traceback (most recent call last):
  File "/home/xx/anaconda3/lib/python3.6/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/xx/qq/DARDet-cgh/mmdet/models/backbones/resnet.py", line 482, in __init__
    init_cfg=block_init_cfg)
  File "/home/xx/qq/DARDet-cgh/mmdet/models/backbones/resnet.py", line 557, in make_res_layer
    return ResLayer(**kwargs)
  File "/home/xx/qq/DARDet-cgh/mmdet/models/utils/res_layer.py", line 72, in __init__
    **kwargs))
  File "/home/xx/qq/DARDet-cgh/mmdet/models/backbones/resnet.py", line 30, in __init__
    assert dcn is None, 'Not implemented yet.'
AssertionError: Not implemented yet.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xx/anaconda3/lib/python3.6/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/xx/qq/DARDet-cgh/mmdet/models/detectors/dardet.py", line 77, in __init__
    test_cfg, pretrained)
  File "/home/xx/qq/DARDet-cgh/mmdet/models/detectors/single_stage.py", line 26, in __init__
    self.backbone = build_backbone(backbone)
  File "/home/xx/qq/DARDet-cgh/mmdet/models/builder.py", line 19, in build_backbone
    return BACKBONES.build(cfg)
  File "/home/xx/anaconda3/lib/python3.6/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/xx/anaconda3/lib/python3.6/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/xx/anaconda3/lib/python3.6/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AssertionError: ResNet: Not implemented yet.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 190, in <module>
    main()
  File "tools/train.py", line 164, in main
    test_cfg=cfg.get('test_cfg'))
  File "/home/xx/qq/DARDet-cgh/mmdet/models/builder.py", line 58, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/xx/anaconda3/lib/python3.6/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/xx/anaconda3/lib/python3.6/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/xx/anaconda3/lib/python3.6/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AssertionError: DARDet: ResNet: Not implemented yet.
```
请问一个如何修改？希望您能解答，谢谢！

**Comment by zf020114** [comment]
把配置文件中的关于骨干加DCN的配置行注释掉就可以了
