### ISSUE TITLE
训练

### ISSUE THREAD

**Issue by yzk-lab** [zf020114/DARDet#14]
数据集是dota吗？需要修改些什么地方？我看有个DOTAK和DOTA 需要注意些什么？我训练不起来 报这个错误。
![4W@0$O}3}LV87~@IKN(W})Y](https://user-images.githubusercontent.com/41197028/145025554-6b46ae0d-b4ad-4b6d-ab84-f1eaedcd170a.png)
![Q)XVLEDXJACK$D0DDEATVNN](https://user-images.githubusercontent.com/41197028/145025585-79289f6e-4699-4e48-b212-7532f01b4b17.png)
我的DARDet config的路径改成了如下所示，是哪里出了问题呢？跑不起来呢。
![IYNRPZH$T9T7PGQDO%BO3{N](https://user-images.githubusercontent.com/41197028/145025752-844f72cd-28b0-4b07-a3a1-4671020cb847.png)
![X7$F_K9II$1TTC6I7KAM(3L](https://user-images.githubusercontent.com/41197028/145025770-eb9cffd2-f145-4c61-abd9-b009206fd41c.png)

**Comment by yzk-lab** [comment]
麻烦告知了 ，期待您的解答。谢谢！

**Comment by zf020114** [comment]
这个错误在issue里面有 安装 mmpycocotools就可以了  mmdet官方代码库的 issue里面也有。百度一搜就能搜到。发自我的华为手机-------- 原始邮件 --------发件人： yzk-lab ***@***.***>日期： 2021年12月7日周二 晚上8:03收件人： zf020114/DARDet ***@***.***>抄送： Subscribed ***@***.***>主    题： [zf020114/DARDet] 训练 (Issue #14)

数据集是dota吗？需要修改些什么地方？我看有个DOTAK和DOTA 需要注意些什么？我训练不起来 报这个错误。





我的DARDet config的路径改成了如下所示，是哪里出了问题呢？跑不起来呢。

**Comment by yzk-lab** [comment]
> 这个错误在issue里面有 安装 mmpycocotools就可以了  mmdet官方代码库的 issue里面也有。百度一搜就能搜到。发自我的华为手机-------- 原始邮件 --------发件人： yzk-lab ***@***.***>日期： 2021年12月7日周二 晚上8:03收件人： zf020114/DARDet ***@***.***>抄送： Subscribed ***@***.***>主 题： [zf020114/DARDet] 训练 (Issue #14) 数据集是dota吗？需要修改些什么地方？我看有个DOTAK和DOTA 需要注意些什么？我训练不起来 报这个错误。 我的DARDet config的路径改成了如下所示，是哪里出了问题呢？跑不起来呢。 —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

按照作者你给的建议解决了之前出现的问题，我始终感觉还是数据集的问题，当时就是直接用DOTA_devkit裁剪了图片得到了json格式标签和patch. 我利用的是你给的dardet_r50_fpn_1x_dcn_val.py配置文件。现在训练出现这个问题。
![T31{GAKVGJ$ XSNF9(GRR}M](https://user-images.githubusercontent.com/41197028/145139810-d8ea8438-ecf7-4e72-967f-f001f8db2b1c.png)
配置文件中 我只改了几个路径
![4 Z6K_LA3~I1AEICGLJ1I8Y](https://user-images.githubusercontent.com/41197028/145139963-81e76d1d-3b82-4a86-a9e8-44614a15f369.png)
是还需要注意哪里吗？麻烦告知啦 谢谢 感觉能跑  很想学习你文章。

**Comment by yzk-lab** [comment]
![4B)64 SF} LOHDOUNN5{1I4](https://user-images.githubusercontent.com/41197028/145140135-fc86252c-b40d-4776-bc6c-01b8877ff414.png)

**Comment by yzk-lab** [comment]
![4B)64 SF} LOHDOUNN5{1I4](https://user-images.githubusercontent.com/41197028/145140243-d3a71384-d5db-4ae1-ad2a-92a303a6437e.png)
![6%1}9V4G)QN85N6$TXIXMKS](https://user-images.githubusercontent.com/41197028/145140253-8cb20d4c-221f-4ff7-a11a-4b1148f178c5.png)
![4 Z6K_LA3~I1AEICGLJ1I8Y](https://user-images.githubusercontent.com/41197028/145140265-b7cd305e-b185-499c-aba5-171eead3bc47.png)
![6Z1M) 0)X~D{ F7NNC({_44](https://user-images.githubusercontent.com/41197028/145140273-189cbd9d-b08f-4ceb-be18-c33a5d52172d.png)

**Comment by VV-DL-JUMP** [comment]
这个需要把DOTA2COCOTrain函数里的imageparent和labelparent也指向到自己训练的数据路径

**Comment by Lg955** [comment]
我想在训练的时候加上eval，但是一直报错，我怀疑是config文件出问题了，但不确定是不是，想请教一下。
报错（图片**点击可放大**）
![image](https://user-images.githubusercontent.com/69025725/168314129-02429d0e-ea38-4211-a320-a4ee979ca07e.png)

config文件：
![image](https://user-images.githubusercontent.com/69025725/168314443-c0b8155b-b68e-4815-8ad8-7814942ef8bb.png)


`gt_dir='/dataset/lg_datacode/Rotation_Data/DARDet_data/dota_1024_DARDet_label1.0/val1024/labelTxt/'`文件夹下的内容：
![image](https://user-images.githubusercontent.com/69025725/168315352-297a665f-546a-4d48-9e05-faf88d0c5e1e.png)

`gt_dir='/dataset/lg_datacode/Rotation_Data/DARDet_data/dota_1024_DARDet_label1.0/val1024`文件夹下的内容：
![image](https://user-images.githubusercontent.com/69025725/168315628-cad4315e-b703-4e98-a0fe-f8255b2cdb90.png)

**我有几个问题想问一下**：
1、训练的时候验证eval使用的是`evaluation = dict(……)`还是`val=dict(……)`？
2、`evaluation = dict(……)`里面`gt_dir=`下`labelTxt`中包含的应该是gt的坐标文件还是应该包含其他文件？
3、造成训练错误`ZeroDivisionError: division by zero`的原因是什么啊？

**Comment by Lg955** [comment]
- Traceback (most recent call last):
File "tools/train.py", line 191, in
main()
File "tools/train.py", line 188, in main
meta=meta)
File "/dataset/lg_datacode/code/DARDet/mmdet/apis/train.py", line 176, in train_detector
runner.run(data_loaders, cfg.workflow)
File "/home/lg/anaconda3/envs/dardet/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
epoch_runner(data_loaders[i], **kwargs)
File "/home/lg/anaconda3/envs/dardet/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
for i, data_batch in enumerate(self.data_loader):
File "/home/lg/anaconda3/envs/dardet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 279, in iter
return _MultiProcessingDataLoaderIter(self)
File "/home/lg/anaconda3/envs/dardet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 746, in init
self._try_put_index()
File "/home/lg/anaconda3/envs/dardet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 861, in _try_put_index
index = self._next_index()
File "/home/lg/anaconda3/envs/dardet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 339, in _next_index
return next(self._sampler_iter) # may raise StopIteration
File "/home/lg/anaconda3/envs/dardet/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 200, in iter
for idx in self.sampler:
File "/dataset/lg_datacode/code/DARDet/mmdet/datasets/samplers/group_sampler.py", line 36, in iter
indices = np.concatenate(indices)
File "<array_function internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

when I use `./tools/dist_train.sh configs/DARDet/dardet_r50_fpn_1x_dcn_rotate_train.py 4,` everything is OK;

but when use `python tools/train.py configs/DARDet/dardet_r50_fpn_1x_dcn_rotate_train.py`, it will cause the error.

What will cause this?

**Comment by Lg955** [comment]
> * Traceback (most recent call last):
>   File "tools/train.py", line 191, in
>   main()
>   File "tools/train.py", line 188, in main
>   meta=meta)
>   File "/dataset/lg_datacode/code/DARDet/mmdet/apis/train.py", line 176, in train_detector
>   runner.run(data_loaders, cfg.workflow)
>   File "/home/lg/anaconda3/envs/dardet/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
>   epoch_runner(data_loaders[i], **kwargs)
>   File "/home/lg/anaconda3/envs/dardet/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
>   for i, data_batch in enumerate(self.data_loader):
>   File "/home/lg/anaconda3/envs/dardet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 279, in iter
>   return _MultiProcessingDataLoaderIter(self)
>   File "/home/lg/anaconda3/envs/dardet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 746, in init
>   self._try_put_index()
>   File "/home/lg/anaconda3/envs/dardet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 861, in _try_put_index
>   index = self._next_index()
>   File "/home/lg/anaconda3/envs/dardet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 339, in _next_index
>   return next(self._sampler_iter) # may raise StopIteration
>   File "/home/lg/anaconda3/envs/dardet/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 200, in iter
>   for idx in self.sampler:
>   File "/dataset/lg_datacode/code/DARDet/mmdet/datasets/samplers/group_sampler.py", line 36, in iter
>   indices = np.concatenate(indices)
>   File "<array_function internals>", line 6, in concatenate
>   ValueError: need at least one array to concatenate
> 
> when I use `./tools/dist_train.sh configs/DARDet/dardet_r50_fpn_1x_dcn_rotate_train.py 4,` everything is OK;
> 
> but when use `python tools/train.py configs/DARDet/dardet_r50_fpn_1x_dcn_rotate_train.py`, it will cause the error.
> 
> What will cause this?

解决了，问题出在`DOTA_devkit/DOTA2COCO.py/ def DOTA2COCOTrain（）`
https://github.com/zf020114/DARDet/blob/f77f3280cbb141e23b1e8ba045d84458dff1d88b/DOTA_devkit/DOTA2COCO.py#L152-L153
`train2017` 和`train2017labelTxt`要分别改为`images`和`labelTxt`，否则创建的json文件不会包含图像。同时注意也要把`def DOTA2COCOval`函数也改一下
