### ISSUE TITLE
复现问题。按照README.md构建了环境及数据集，但是在训练时出现了以下问题，是在是找不出是什么原因了.....。生成的DOTA1_5_trin1024.json的样式也在下面进行了展示

### ISSUE THREAD

**Issue by cc0616** [zf020114/DARDet#18]
2022-05-06 20:30:29,371 - mmdet - INFO - Start running, host: pc@zcc-Precision-7920-Tower, work_dir: /home/pc/cengxu/NO.9/DARDet-master/workdir/DARDet_r50_2080base
2022-05-06 20:30:29,371 - mmdet - INFO - workflow: [('train', 1)], max: 36 epochs
Traceback (most recent call last):
  File "tools/train.py", line 190, in <module>
    main()
  File "tools/train.py", line 187, in main
    meta=meta)
  File "/home/pc/cengxu/NO.9/DARDet-master/mmdet/apis/train.py", line 175, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/pc/anaconda3/envs/dar/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/pc/anaconda3/envs/dar/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/pc/anaconda3/envs/dar/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/pc/anaconda3/envs/dar/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/pc/anaconda3/envs/dar/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/pc/anaconda3/envs/dar/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
TypeError: __init__() missing 4 required positional arguments: 'casting', 'from_', 'to', and 'i'

DORA1_5train1024.json
{"images": [{"file_name": "296__1__0___0.JPG", "id": 1, "width": 800, "height": 800}, {"file_name": "55__1__0___0.JPG", "id": 2, "width": 800, "height": 800}, {"file_name": "196__1__0___0.JPG", "id": 3, "width": 800, "height": 800}, {"file_name": "306__1__0___0.JPG", "id": 4, "width": 800, "height": 800},..............{"category_id": 1, "segmentation": [[347, 200, 473, 219, 468, 250, 343, 231]], "iscrowd": 0, "bbox": [343, 200, 130, 50], "area": 6500, "image_id": 203, "id": 557}, {"category_id": 1, "segmentation": [[382, 343, 409, 346, 405, 381, 378, 378]], "iscrowd": 0, "bbox": [378, 343, 31, 38], "area": 1178, "image_id": 203, "id": 558}, {"category_id": 1, "segmentation": [[370, 484, 395, 487, 391, 519, 366, 516]], "iscrowd": 0, "bbox": [366, 484, 29, 35], "area": 1015, "image_id": 203, "id": 559}]}

**Comment by Lg955** [comment]
@cc0616  参考这个  https://github.com/zf020114/DARDet/issues/6#issuecomment-1105280277
