### ISSUE TITLE
复现问题

### ISSUE THREAD

**Issue by Cloud-Jowen** [zf020114/DARDet#20]
复现时模型验证出现问题,报错如下
Traceback (most recent call last):
  File "/home/zhangxue/CV_code/DARDet/tools/train.py", line 202, in <module>
    main()
  File "/home/zhangxue/CV_code/DARDet/tools/train.py", line 185, in main
    train_detector(
  File "/home/zhangxue/CV_code/DARDet/mmdet/apis/train.py", line 176, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/zhangxue/anaconda3/envs/dardet/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/zhangxue/anaconda3/envs/dardet/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/zhangxue/anaconda3/envs/dardet/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/zhangxue/CV_code/DARDet/mmdet/core/evaluation/eval_hooks.py", line 147, in after_train_epoch
    key_score = self.evaluate(runner, results)
  File "/home/zhangxue/CV_code/DARDet/mmdet/core/evaluation/eval_hooks.py", line 176, in evaluate
    eval_res = self.dataloader.dataset.evaluate(
  File "/home/zhangxue/CV_code/DARDet/mmdet/datasets/dota_k.py", line 566, in evaluate
    self.evaluate_rbox(results, eval_dir, gt_dir)
  File "/home/zhangxue/CV_code/DARDet/mmdet/datasets/dota_k.py", line 615, in evaluate_rbox
    rec, prec, ap = voc_eval(detpath,
  File "/home/zhangxue/CV_code/DARDet/DOTA_devkit/dota_evaluation_task1.py", line 169, in voc_eval
    print('class_recs[image_ids[d]]',class_recs[image_ids[d]])
KeyError: 'P0179'
是我需要修改哪些路径吗,验证集使用dota2coco格式的还是未转换的

**Comment by Lg955** [comment]
我也有同样的报错，兄弟解决了吗？

**Comment by Lg955** [comment]
> 复现时模型验证出现问题,报错如下"/home/zhangxue/CV_code/DARDet/DOTA_devkit/dota_evaluation_task1.py", line 169, in voc_eval print('class_recs[image_ids[d]]',class_recs[image_ids[d]]) KeyError: 'P0179' 是我需要修改哪些路径吗,验证集使用dota2coco格式的还是未转换的

验证集labelTxt文件夹不要使用分割之后的，使用原始的labelTxt文件夹就不报错了
