### ISSUE TITLE
'COCO' object has no attribute 'get_cat_ids'

### ISSUE THREAD

**Issue by liliwannian** [zf020114/DARDet#3]
First of all, thank you for your contribution.I encountered the following problems when reproducing your code.Rsaicp2_new is my own dataset.When I tried to train, the following problems occurred.

error:
```
Traceback (most recent call last):
  File "tools/train.py", line 190, in <module>
    main()
  File "tools/train.py", line 167, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/tongjiaxing/competition/DARDet-cgh/mmdet/datasets/builder.py", line 67, in build_dataset
    build_dataset(cfg['dataset'], default_args), cfg['oversample_thr'])
  File "/home/tongjiaxing/competition/DARDet-cgh/mmdet/datasets/builder.py", line 71, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/tongjiaxing/anaconda3/envs/dar/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AttributeError: Rsaicp2_new: 'COCO' object has no attribute 'get_cat_ids'
```

I hope you can answer the questions in your busy schedule.

**Comment by zf020114** [comment]
Thank you very much for your interest in our work. 
I think the problem comes from the file changes the API names for COCO in the coco.py file.
You can fix the bug by  reinstall the mmdet compatible version of cocoAPI by
 pip install -U "git+https://github.com/open-mmlab/cocoapi.git#subdirectory=pycocotools"

**Comment by zf020114** [comment]
You can see 
https://github.com/open-mmlab/mmdetection/issues/2913

**Comment by liliwannian** [comment]
It has been resolved, thank you very much.
